export const START_GET_ADS='START_GET_ADS';
export const GET_ADS_SUCCESS='GET_ADS_SUCCESS';
export const GET_ADS_FAILURE='GET_ADS_FAILURE';
export const START_SAVE_AD='START_SAVE_AD';
export const SAVE_AD_SUCCESS='SAVE_AD_SUCCESS'
export const SAVE_AD_FAILURE='SAVE_AD_FAILURE'
export const START_GET_TAGS='START_GET_TAGS';
export const GET_TAGS_SUCCESS='GET_TAGS_SUCCESS';
export const GET_TAGS_FAILURE='GET_TAGS_FAILURE';
// export const FILTER_PRICE='FILTER_PRICE';
// export const FILTER_PRICE='FILTER_NAME';
export const SAVE_USER='SAVE_USER';

